import { StyleSheet } from "react-native";

export const Styles = ({ width, height, isPortrait }) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#152019",
    },
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: "#152019",
        paddingVertical: 10,
        paddingHorizontal: isPortrait ? width * 0.05 : height * 0.15,
    },
    headerContainer: {
        flexDirection: 'row',
        gap: 10,
        paddingTop: 10,
        paddingBottom: 12,
        backgroundColor: '#152019',
        paddingHorizontal: isPortrait ? 0 : "1%", 
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    headerSubtitle: {
        fontSize: 16,
        color: '#AAAAAA',
        fontWeight: '400',
    },
    sectionContainer: {
        marginBottom: 25,
        backgroundColor: '#1C1F1D',
        borderRadius: 12,
        padding: 20,
        borderWidth: 1,
        borderColor: '#404040',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        paddingBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#404040',
    },
    sectionDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: '#4CAF50',
        marginRight: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    fieldLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#FFFFFF',
        marginBottom: 8,
        marginTop: 5,
    },
    inputField: {
        backgroundColor: '#4A4A4A',
        borderWidth: 1,
        borderColor: '#555555',
        borderRadius: 8,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 15,
        color: '#FFFFFF',
        marginBottom: 15,
        minHeight: 45,
    },
    textArea: {
        minHeight: 80,
        textAlignVertical: 'top',
        paddingTop: 12,
    },
    dropdownStyle: {
        backgroundColor: '#4A4A4A',
        borderColor: '#555555',
        borderRadius: 8,
        minHeight: 45,
        marginBottom: 15,
        paddingHorizontal: 15,
    },
    dropDownContainerStyle: {
        backgroundColor: '#4A4A4A',
        borderColor: '#555555',
        borderRadius: 8,
        marginTop: 2,
        zIndex: 9999,
        maxHeight: 200,
    },
    vehicleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 15,
    },
    vehicleTypeContainer: {
        flex: 1,
    },
    licensePlateContainer: {
        flex: 1,
    },
    buttonContainer: {
        borderRadius: 10,
        marginBottom: 25,
    },
    submitButton: {
        backgroundColor: 'transparent',
        borderRadius: 12,
        paddingVertical: 3,
        elevation: 3,
        shadowColor: '#4CAF50',
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    submitButtonLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FFFFFF',
    },
    // Legacy styles for backwards compatibility
    nameContainer: {
        flexDirection: "row",
        justifyContent: "center",
        gap: isPortrait ? "4%" : "3%",
        width: "100%",
    },
    nameField: {
        width: isPortrait ? "48%" : "48.5%",
        backgroundColor: '#4A4A4A',
        borderWidth: 1,
        borderColor: '#555555',
        borderRadius: 8,
        marginVertical: 8,
        paddingHorizontal: 15,
        fontSize: 15,
        color: '#FFFFFF',
        minHeight: 45,
    },
    button: {
        justifyContent: 'center',
        alignContent: 'center',
        marginVertical: 8,
        borderRadius: 10,
        width: '100%',
        height: 45,
        backgroundColor: '#4CAF50',
    },
    buttonLabelStyle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '600',
    },
});