import { StyleSheet } from 'react-native';

export const Styles = ({ width, height, isPortrait }) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#0A0A0A',
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingTop: 10,
        paddingBottom: 12,
        marginHorizontal: isPortrait ? 0 : "1%",
        backgroundColor: '#0A0A0A',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#FFFFFF',
        marginBottom: 5,
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#1E90FF',
        marginBottom: isPortrait ? width * 0.03 : height * 0.03,
        paddingVertical: 12,
        borderRadius: 12,
        elevation: 2,
        shadowColor: '#1E90FF',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        marginLeft: 8,
    },
    searchBarContainer: {
        flexDirection: "row",
        gap: 12,
    },
    searchBar: {
        marginBottom: isPortrait ? width * 0.03 : height * 0.03,
        height: 48,
        borderRadius: 12,
        backgroundColor: "#1A1A1A",
        borderWidth: 1,
        borderColor: '#2A2A2A',
        elevation: 0,
        width: "63%",
    },
    searchBarInput: {
        marginTop: isPortrait ? "-1.5%" : "-0.7%",
        height: 48,
        color: "#fff",
        fontSize: 14,
    },
    clearIcon: {
        zIndex: 9999,
        tintColor: '#fff',
    },
    scrollContainer: {
        flexGrow: 1,
        backgroundColor: '#0A0A0A',
        paddingHorizontal: isPortrait ? width * 0.04 : height * 0.15,
    },
    subContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dropdown: {
        borderRadius: 12,
        backgroundColor: "#1A1A1A",
        borderWidth: 1,
        borderColor: '#2A2A2A',
        borderRadius: 8,
        minHeight: 47,
        width: "33%",
        paddingHorizontal: 10,
    },
    dropdownContainer: {
        backgroundColor: '#1A1A1A',
        borderColor: "#2A2A2A",
        borderRadius: 8,
        maxHeight: 500,
        width: "33%",
    },
    placeholder: {
        color: '#888',
        fontSize: 14,
    },
    text: {
        color: '#fff',
        fontSize: 14,
    },
    arrowIcon: {
        tintColor: '#888',
    },
    tickIcon: {
        tintColor: '#fff',
    },
    iconContainer: {
        right: 10,
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    gridItem: {
        width: isPortrait ? '100%' : '48%',
        marginBottom: 12,
    },
    card: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#1A1A1A',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#2A2A2A',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardContent: {
        flex: 1,
    },
    cardTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    numberBadge: {
        backgroundColor: '#00CBA9',
        borderRadius: 8,
        paddingVertical: 5,
        marginRight: 12,
        minWidth: 35,
        alignItems: 'center',
        justifyContent: 'center',
    },
    textBadge: {
        backgroundColor: '#FFC107',
        borderRadius: 8,
        paddingVertical: 5,
        marginRight: 12,
        minWidth: 35,
        alignItems: 'center',
        justifyContent: 'center',
    },
    badgeText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    cardTitle: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    cardDetails: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 5,
    },
    cardSubtitle: {
        color: '#999',
        fontSize: 13,
        marginBottom: 2,
    },
    cardDate: {
        color: '#B0BEC5',
        fontSize: 14,
    },
    iconButtonContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'flex-end',
        position: 'absolute',
        top: 0,
        right: -12,
    },
    iconButton: {
        position: 'absolute',
        top: -10,
        right: -10,
        padding: 8,
    },
    nodatacontainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    noDataText: {
        color: '#999',
        fontSize: 14,
    },
});