import { StyleSheet } from "react-native";

export const Styles = (theme) => StyleSheet.create({
    b_bottom: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "#1C2731",
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 10,
        boxShadow:'rgba(99, 102, 241, 0.506) 0px 0px 20.0895px 0px',
    },
    bottom_container: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    bottom_tab: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "transparent",
        borderRadius: 15,
    },
    active_icon: {
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#fff",
        borderRadius: 100,
        padding: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
    },
    active_text: {
        color: '#fff',
        fontWeight: 'bold',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 5,
        marginTop: 2,
        fontSize: 12,
    },
    bottom_activetab: {
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 15,
        boxShadow:'rgba(99, 102, 241, 0.506) 0px 0px 20.0895px 0px',
    },
    iconContainer: {
        padding: 3,
        borderRadius: 8,
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 10,
    },
    inactiveText: {
        color: '#4a6682',
        fontWeight: 'thin',
        marginTop: 5,
        fontSize: 12,
    },
});