import { StyleSheet } from "react-native";

export const Styles = ({ width, height, isPortrait }) => StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#12171C",
    },
    scrollContainer: {
        flexGrow: 1,
        alignContent: "center",
        paddingVertical: isPortrait ? "4%" : "2%",
        paddingHorizontal: isPortrait ? "3%" : "3%",
        backgroundColor: "#12171C",
    },
    header: {
        flexDirection: "row",
        justifyContent: "center",
        alignContent: "center",
        gap: 10,
    },
    headerText: {
        color: "#1A78D4",
        fontSize: 17,
        fontWeight: "bold",
    },
    heading: {
        fontSize: 15,
        fontWeight: "bold",
        marginTop: 10,
        marginBottom: 20,
        color: "#B0BEC5",
        textAlign: "center",
    },
    cardContainer: {
        flex: 1,
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "center",
        alignItems: "center",
        gap: 15,
        marginBottom: 15,
        width: "100%",
    },
    cardContentContainer: {
        padding: 12,
        borderRadius: 10,
        width: "47.9%",
    },
    contentWrap: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "space-between",
    },
    cardTitle: {
        color: "#D2E3F4",
        fontWeight: "bold",
        marginTop: 5,
        fontSize: 13,
    },
    iconMainContainer: {
        padding: 10,
        paddingBottom: 18,
        paddingLeft: 18,
        position: "absolute",
        borderTopRightRadius: 10,
        borderBottomLeftRadius: 50,
    },
    iconContainer: {
        padding: 8,
        borderRadius: 12,
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 10,
    },
    cardSubTitle: {
        textAlign: "left",
        fontSize: 30,
        color: "#fff",
        fontWeight: "bold",
    },
    textContainer: {
        flex: 1,
        marginTop: 10,
    },
    cardText: {
        color: "#BACFE7",
        fontSize: 13,
    },
    headingTwoContainer: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
        marginTop: 25,
        marginBottom: 20,
    },
    headingTwo: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#fff",
    },
    divider: {
        borderColor: "#1E86E3",
        borderWidth: 1,
        width: isPortrait ? "57%" : "70%",
        alignSelf: "center",
    },
    analyticsContainer: {
        gap: 12,
        marginBottom: 20,
        marginHorizontal: !isPortrait && "3%",
    },
    analyticsCard: {
        backgroundColor: "#1E242B",
        borderRadius: 10,
        padding: 15,
        elevation:105,
    },
    analyticsHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    analyticsValue: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#fff",
        marginTop: 5,
    },
    analyticsProgressContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    analyticsLabelContainer: {
        flexDirection: "row",
        gap: 10,
    },
    analyticsLabel: {
        fontSize: 13,
        color: "#BACFE7",
        marginTop: 2,
    },
    analyticsIconContainer: {
        position: "absolute",
        right: 0,
        top: "1%",
        backgroundColor: "#a64dff",
        padding: 8,
        borderRadius: 10,
        elevation: 10,
    },
    progressLine: {
        height: 2,
        width: "90%",
        backgroundColor: "transparent",
        borderRadius: 5,
    },
    regiterButtonContainer: {
        flex: 1,
        justifySelf: "center",
        alignSelf: "center",
        paddingVertical: 3,
        borderRadius: 10,
        elevation: 10,
        boxShadow: "rgba(99, 102, 241, 0.776) 0px 0px 29.2732px 0px",
        width: isPortrait ? "100%" : "90%",
    },
    registerButton: {
        backgroundColor: "transparent",
    },
    registerButtonLabel: {
        color: "#fff",
    },
    grpBtn: {
        flex: 1,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginVertical: 15,
        marginHorizontal: isPortrait ? "0%" : "3%",
    },
    buildButton: {
        paddingVertical: 3,
        width: "48%",
        borderRadius: 10,
        backgroundColor: "#1e1e1e",
        borderWidth: 1,
        borderColor: "#1E1E1E"
    },
});