import { StyleSheet } from "react-native";

export const Styles = ({ width, height, isPortrait }) => StyleSheet.create({
    container: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "#1E80DE",
        paddingVertical: !isPortrait && 20,
    },
    animatedWrapper: {
        width: '100%',
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 30,
    },
    iconContainer: {
        backgroundColor: "#213345",
        padding: 15,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "#354758",
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 10,
    },
    heading: {
        fontSize: 30,
        fontWeight: "bold",
        color: "#FFFFFF",
        marginTop: 10,
    },
    subHead: {
        color: "#ACCEEC",
        marginTop: 10,
        marginBottom: 20,
        fontSize: 17,
    },
    formContainer: {
        justifyContent: "center",
        backgroundColor: "#29313B",
        width: isPortrait ? "90%" : "70%",
        padding: 20,
        borderRadius: 15,
        elevation: 10,
        borderWidth: 1,
        borderColor: "#3D4856",
    },
    label: {
        textAlign: "left",
        color: "#EAEBEC",
        marginLeft: 2,
        fontWeight: "bold",
        fontSize: 15,
    },
    inputField: {
        width: "100%",
        height: 50,
        borderWidth: 1,
        borderColor: "#50565B",
        borderRadius: 10,
        backgroundColor: "#252D33",
        marginTop: 4,
        marginBottom: 8,
        fontSize: 15,
    },
    inputFieldContent: {
        color: "#fff",
    },
    button: {
        justifyContent: 'center',
        alignContent: 'center',
        borderWidth: 1,
        borderColor: "#B4B7BA",
        borderRadius: 5,
        backgroundColor: "#626F7B",
        marginVertical: 8,
        paddingVertical: 3,
        width: "100%",
    },
    buttonLabelStyle: {
        color: "#fff",
        fontSize: 18,
    },
    text: {
        marginVertical: 8,
        textAlign: "center",
        fontSize: 15,
        color: "#A3A9AF",
    },
    linkText: {
        fontWeight: "bold",
        color: "#E9EAEC",
        fontSize: 17,
    },
});