import { StyleSheet } from "react-native";

export const Styles = ({ width, height, isPortrait }) => StyleSheet.create({
    container: {
        flex: 1,
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: "center",
        alignItems: "center",
        paddingVertical: !isPortrait && height * 0.08,
    },
    iconContainer: {
        backgroundColor: "#472923",
        padding: 15,
        borderRadius: 20,
        borderWidth: 2,
        borderColor: "#5A3E39",
        shadowColor: '#fff',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.8,
        shadowRadius: 4,
        elevation: 10,
    },
    heading: {
        fontSize: 25,
        fontWeight: "bold",
        color: "#FFFFFF",
        marginTop: 10,
    },
    subHead: {
        color: "#FBDED8",
        marginTop: 10,
        marginBottom: 20,
        fontSize: 17,
    },
    formContainer: {
        justifyContent: "center",
        backgroundColor: "#4A3820",
        width: isPortrait ? "90%" : "70%",
        padding: 20,
        borderRadius: 15,
        elevation: 10,
        borderWidth: 2,
        borderColor: "#5B423A",
    },
    label: {
        textAlign: "left",
        color: "#EAEBEC",
        marginLeft: 2,
        fontWeight: "bold",
        fontSize: 15,
    },
    nameContainer: {
        flexDirection: "row",
        justifyContent: "center",
        gap: isPortrait ? "4%" : "3%",
        width: "100%",
    },
    nameFieldContainer: {
        flexDirection: "column",
        justifyContent: "center",
        alignContent: "center",
        width: "48%",
        marginBottom: 10,
    },
    inputField: {
        width: "100%",
        height: 45,
        borderWidth: 1,
        borderColor: "#61524D",
        borderRadius: 10,
        backgroundColor: "#3B2822",
        marginTop: 4,
        marginBottom: 8,
        fontSize: 15,
        color: "#fff",
    },
    button: {
        justifyContent: 'center',
        alignContent: 'center',
        borderWidth: 1,
        borderColor: "#B4B7BA",
        borderRadius: 5,
        backgroundColor: "#7F6F65",
        marginVertical: 8,
        paddingVertical: 3,
        width: "100%",
    },
    buttonLabelStyle: {
        color: "#fff",
        fontSize: 18,
    },
    text: {
        marginVertical: 8,
        textAlign: "center",
        fontSize: 15,
        color: "#C8C3BD",
    },
    linkText: {
        fontWeight: "bold",
        color: "#EDEBE9",
        fontSize: 17,
    },
});